add command for Git hook distribution

diff --git a/bin/git-hooks/post-checkout b/bin/git-hooks/post-checkout
--- a/bin/git-hooks/post-checkout
+++ b/bin/git-hooks/post-checkout
@@ -6,45 +6,44 @@
 #
 
 
-# check for and execute an existing user hook
-if [ -f "$0.user" ]; then
-   "$0.user" "$@"
+echo runnning: $0
+set | grep GIT
+
+
+# execute an existing user hook
+if [ -x "$0.user" ]; then
+   "$0.user" "$@" || exit $?
 fi
 
 
-# check for Composer
+# find Composer
 result=$(type -P composer.phar 2> /dev/null)
-if [ -z $result ]; then
+if [ -z "$result" ]; then
     result=$(type -P composer 2> /dev/null)
-    [ -z $result ] && echo "ERROR: could not find Composer" && exit 1
+    [ -z "$result" ] && echo "ERROR: could not find Composer" && exit 1
 fi
-if [ ".$OSTYPE" = ".msys" ] || [ ".$OSTYPE" = ".cygwin" ] ; then
-   if [ ".$TERM" != ".cygwin" ]; then
-      # Windows: respect an existing Composer alias in an interactive shell
-      use_alias=1
-   fi
+if [[ ".$OSTYPE" = ".msys" || ".$OSTYPE" = ".cygwin" ]]; then
+   # Windows: In interactive shells (i.e. MinTTy) use an existing alias to prevent terminal color support issues.
+   [ ".$TERM" != ".cygwin" ] && use_alias=1 
 fi
 
 
-# get changed file names
+# get the changed files
 changed_files=$(git diff-tree -r --name-only --no-commit-id $1 $2)
 
 
-# run Composer if lock file has changed
+# check if composer.lock has changed and run Composer
 check_run() {
    [ -f "$1" ]                                     && \
-   echo "$changed_files" | grep --quiet -Fx "$1"   && \
+   #echo "$changed_files" | grep --quiet -Fx "$1"   && \
    echo " * changes detected in $1"                && \
    echo " * running composer install"              && \
-   run_composer=1
-   
-   if [ -n $run_composer ]; then
-      if [ -n $use_alias ] && [ -f "${HOME}/.bash_aliases" ]; then
-         . "${HOME}/.bash_aliases"
-         shopt -s expand_aliases
-      fi
-      COMPOSER_ALLOW_SUPERUSER=1
-      eval "composer install"
+   {
+   if [[ -n "$use_alias" && -f ~/.bash_aliases ]]; then
+      shopt -s expand_aliases
+      . ~/.bash_aliases
    fi
+   eval "COMPOSER_ALLOW_SUPERUSER=1 composer install"
+   }
 }
 check_run 'composer.lock'
