update git hooks

diff --git a/bin/git-hooks/post-checkout b/bin/git-hooks/post-checkout
--- a/bin/git-hooks/post-checkout
+++ b/bin/git-hooks/post-checkout
@@ -12,12 +12,19 @@ if [ -f "$0.user" ]; then
 fi
 
 
-# check existence of Composer
+# check and configure Composer
 result=$(type -P composer.phar 2> /dev/null)
-if [ "$result" == "" ]; then
+if [ ".$result" == "." ]; then
     result=$(type -P composer 2> /dev/null)
-    [ "$result" == "" ] && echo " * error: could not find Composer" && exit 1
+    [ ".$result" == "." ] && echo "ERROR: could not find Composer" && exit 1
 fi
+if [ ".$OSTYPE" = ".msys" ] || [ ".$OSTYPE" = ".cygwin" ] ; then
+    if [ ".$BASH_VERSION" != "." ]; then
+        # if running bash in msys or cygwin
+        ansi='--ansi'
+    fi
+fi
+COMPOSER_ALLOW_SUPERUSER=1
 
 
 # get changed file names
@@ -29,9 +36,9 @@ check_run() {
     echo "$changed_files" | grep --quiet -Fx "$1"   && \
     echo " * changes detected in $1"                && \
     echo " * running $2"                            && \
-    eval "$2"
+    composer $ansi install
 }
 
 
-# run command if file has changed
-check_run 'composer.lock' 'composer install'
+# run composer if lock file has changed
+check_run 'composer.lock'
