update Git hook setup

diff --git a/bin/git/post-merge b/bin/git/post-merge
--- a/bin/git/post-merge
+++ b/bin/git/post-merge
@@ -1,64 +1,84 @@
 #!/bin/bash
 #
-# Git hook to run "composer install" if the file "composer.lock" was changed.
+# Git hook to automatically execute Composer commands after a Git merge. If the file "composer.lock" was modified by the
+# merge the command "composer install" is executed. If the file "composer.lock" was not modified by the merge the command
+# "composer dump-autoload" is executed.
+#
 #
 # Notes:
 # ------
-#  - This hook is not executed by Eclipse.
-
 #  - The hook is not executed if merging failed due to conflicts.
-#  - The hook is not executed if you run pull with --rebase option.
+#  - The hook is not executed if "git pull" is run with the --rebase option.
+#  - If the hook is not executed automatically the Composer commands have to be called manually.
+#  - Whether or not hooks are executed by a graphical Git replacement depends on the tool. For example the JGit
+#    implementation of Eclipse atm does not execute hooks.
 #
+#
+# Comments:
+# ---------
 #  - post-rewrite works for me. As side effect it is also executed on amend.
 #    @see  http://stackoverflow.com/questions/21307744/git-post-rebase-hook
-#
 #  - I would check updated submodules too:
 #    check_run .gitmodules "git submodule init && git submodule update"
+#
+set -e
 
 
-# Execute an existing user hook.
-if [ -x "$0.user" ]; then
-    "$0.user" "$@" || exit $?
-fi
+# --- functions -------------------------------------------------------------------------------------------------------------
+
+# print a message to stderr
+function error() {
+    echo "error: $@" 1>&2
+}
 
 
-# Check user aliases and get an existing Composer definition.
+# check user aliases and get an existing Composer alias
+COMPOSER_ALIAS=
+COMPOSER_ALIAS_CHECKED=
 function check_composer_alias() {
     if [[ -z "$COMPOSER_ALIAS_CHECKED" && -f ~/.bash_aliases ]]; then
-        . ~/.bash_aliases 
+        . ~/.bash_aliases
         COMPOSER_ALIAS=${BASH_ALIASES[composer]:-${BASH_ALIASES[composer.phar]}}
-        unalias -a 
+        unalias -a
     fi
     COMPOSER_ALIAS_CHECKED=done
 }
-COMPOSER_ALIAS=; COMPOSER_ALIAS_CHECKED=
+
+# --- end of functions ------------------------------------------------------------------------------------------------------
 
 
-# Find Composer.
-composer=$(type -P composer)
-composer=${composer:-$(type -P composer.phar)}
-[ -z "$composer" ] && { check_composer_alias; composer=$COMPOSER_ALIAS; }
-[ -z "$composer" ] && echo "ERROR: could not find Composer" && exit 1
+# execute an existing user hook
+[ -x "$0.user" ] && "$0.user" "$@"
 
 
-# Check for Cygwin terminal with color issues. Use an existing alias as workaround.
+# find Composer
+COMPOSER=$(type -P composer)
+COMPOSER=${COMPOSER:-$(type -P composer.phar)}
+[ -z "$COMPOSER" ] && { check_composer_alias; composer=$COMPOSER_ALIAS; }
+[ -z "$COMPOSER" ] && { error "ERROR: could not find Composer"; exit 1; }
+
+
+# check for a Cygwin terminal and use an existing alias as workaround for possible color issues
 CYGWIN=$(type -P cygpath.exe)
 if [[ -n "$CYGWIN" && "$TERM" == *"color"* ]]; then
     check_composer_alias
-    composer=${COMPOSER_ALIAS:-$composer}
-fi    
+    COMPOSER=${COMPOSER_ALIAS:-$COMPOSER}
+fi
 
 
-# Get the changed files from Git.
-changed_files=$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)
+# get the changed files from Git
+CHANGED_FILES=$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)
 
 
-# Check if composer.lock has changed and run Composer.
-function check_and_run() {
-    [ -f "$1" ]                                                                  && \
-    echo "$changed_files" | grep --quiet -Fx "$1"                                && \
-    echo " * changes detected in $1"                                             && \
-    echo " * running composer install"                                           && \
-    COMPOSER_ALLOW_SUPERUSER=1 $composer install --ignore-platform-reqs --no-dev
+# check "composer.lock" for modifications and run the according Composer command
+function check_lockfile() {
+    LOCKFILE='composer.lock'
+    if [[ -f "$LOCKFILE" && $(echo "$CHANGED_FILES" | grep --quiet -Fx "$LOCKFILE") ]]; then
+        echo " * changes detected in $LOCKFILE"
+        echo " * running composer install"
+        COMPOSER_ALLOW_SUPERUSER=1 $COMPOSER install --ignore-platform-reqs --no-dev
+    else
+        COMPOSER_ALLOW_SUPERUSER=1 $COMPOSER dump-autoload
+    fi
 }
-check_and_run 'composer.lock'
+check_lockfile
